config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "people#index"
  resources :projects
end

app/models/person.rb
class Person
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated

  field :name, type: String
  field :street, type: String
  field :city, type: String
  field :state, type: String
  field :country, type: String

end

app/models/project.rb
class Project
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated
  field :title, type: String
  field :start_date, type: Date
  field :end_date, type: Date
  field :category, type: Integer


  embedded_in :user
 
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
  embeds_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authenticate_user!
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :street, :city, :state)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

	def index

		@projects = current_user.projects
	end

	def new 
		@project = Project.new
	end
	def show
		@project = current_user.projects.where(id:params[:id]).last
	end
	def destroy
		project = current_user.projects.where(id:params[:id]).last
		project.destroy if project.present?
		# redirect_to projects_path
	end
	def create
		@project = current_user.projects.build(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
	end


	private 

	def project_params
		params.require(:project).permit(:title, :start_date, :end_date, :category)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li>
        <%= link_to "Projects embedded_in embeds_many", projects_path%>
      </li>
      <li><a href="#">Student has_many_through</a></li>
      <li><a href="#">Page 3</a></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MongoRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css">
<script type="text/javascript" src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.min.js'></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/nav"%>
    <div class="container">
    <%= yield %>
            
    </div>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

    <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

    <div class="field">
    <%= form.label :country_id %>
    <%= form.text_field :country_id %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.street %></td>
        <td><%= person.city %></td>
        <td><%= person.state %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Street:</strong>
  <%= @person.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @person.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @person.state %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/projects/_form.html.erb
<%= form_for(@project, local: true,html:{class:"form-horizontal"}) do |form| %>


<!-- Text input http://getbootstrap.com/css/#forms -->
<div class="form-group">
  <label for="textinput" class="control-label col-sm-2">Project Title</label>
  <div class="col-sm-10">
    <%=form.text_field :title,class:"form-control",placeholder:"Title"%>
  </div>
</div>
<!-- Text input http://getbootstrap.com/css/#forms -->
<div class="form-group">
  <label for="textinput" class="control-label col-sm-2">Start Date</label>
  <div class="col-sm-10">
      <%=form.text_field :start_date,type:"date",class:"form-control",placeholder:"start date"%>
  </div>
</div>
<div class="form-group">
  <label for="textinput" class="control-label col-sm-2">End Date</label>
  <div class="col-sm-10">
     <%=form.text_field :end_date,type:"date",class:"form-control",placeholder:"end date"%>
  </div>
</div>
<div class="form-group">
  <label for="textinput" class="control-label col-sm-2">Category</label>
  <div class="col-sm-10">
<%=form.select :category,options_for_select((1..5).step(1)),class:"form-control",placeholder:"end date"%>
  </div>
</div>
<!-- Button http://getbootstrap.com/css/#buttons -->
<div class="form-group">
  <label class="control-label col-sm-2" for="singlebutton">Save project</label>
  <div class="text-right col-sm-10">
    <%= form.submit%>
  </div>
</div>



<% end %>

app/views/projects/index.html.erb
<%= link_to "add new project", new_project_path,class:"btn btn-success"%>
<h1>Projects</h1>

<table class="table table-hover">
	<thead>
		<tr>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @projects.each do |pr| %>
		<tr class="prow">
			<td><%= pr.title %></td>
			<td><%= pr.start_date %></td>
			<td><%= pr.end_date %></td>
			<td><%= pr.category %></td>
			<td><%= pr.created_at %></td>
			<td><%= pr.updated_at %></td>
			<td><%= link_to "delete" ,project_path(pr),method: :delete,remote: :true,class:"ajaxGet"%></td>
			<td><%= link_to "view" ,project_path(pr)%></td>
		</tr>
		<% end %>
	</tbody>
</table>

<script type="text/javascript">
	$(document).ready(function(){
		$(".ajaxGet").on('ajax:success',function(e,data,status,xhr){
			$(this).closest('tr.prow').remove();
		}).on('ajax:error',function(e,xhr,status,error){
			console.log("err")
		})
	})
</script>

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/show.html.erb
<h1>Show project</h1>


<table class="table table-hover">
	<thead>
		<tr>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% pr = @project %>
		<tr>
			<td><%= pr.title %></td>
			<td><%= pr.start_date %></td>
			<td><%= pr.end_date %></td>
			<td><%= pr.category %></td>
			<td><%= pr.created_at %></td>
			<td><%= pr.updated_at %></td>
			<td><%= link_to "delete" ,project_path(pr),method: :delete,remote: :true,class:"ajaxGet"%></td>
			<td><%= link_to "view" ,project_path(pr)%></td>
		</tr>
		<% #end %>
	</tbody>
</table>